### ISSUE TITLE
Firebase Integration

### ISSUE THREAD

**Issue by omar-danasoury** [omar-danasoury/Worood#8]

**Comment by omar-danasoury** [comment]
The error points to this line in the app.module.ts
lines: 28,29
// Initialize Firebase
const app = initializeApp(firebaseConfig);



Uncaught Error: Either AngularFireModule has not been provided in your AppModule (this can be done manually or implictly using
provideFirebaseApp) or you're calling an AngularFire method outside of an NgModule (which is not supported).
    at getSchedulers (angular-fire.mjs:128:15)
    at runOutsideAngular (angular-fire.mjs:134:12)
    at angular-fire.mjs:202:21
    at 635 (app.module.ts:29:26)
    at __webpack_require__ (bootstrap:19:1)
    at 4429 (environment.ts:16:1)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (.*\.entry\.js.*$ include: \.entry\.js$ exclude: \.system\.entry\.js$ namespace object:13:1)
    at .*\.entry\.js.*$ include: \.entry\.js$ exclude: \.system\.entry\.js$ namespace object:13:1
    at __webpack_require__.O (chunk loaded:23:1)

**Comment by omar-danasoury** [comment]
Rolled back to initial commit!

**Comment by omar-danasoury** [comment]
Tested! works good!
Still we need to add the authentication integration @Assadi02, then we can test and close this issue

**Comment by omar-danasoury** [comment]
Works well with no errors!
Completed!
